name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rust-src, wasm32-unknown-unknown

      - name: Install Zola
        run: |
          wget https://github.com/getzola/zola/releases/download/v0.17.2/zola-v0.17.2-x86_64-unknown-linux-gnu.tar.gz
          tar xvf zola-v0.17.2-x86_64-unknown-linux-gnu.tar.gz
          sudo mv zola /usr/local/bin/

      - name: Build WASM
        run: |
          cd energysim-wasm
          cargo build --release --target wasm32-unknown-unknown
          wasm-bindgen --out-dir ../static/wasm --target web target/wasm32-unknown-unknown/release/energysim_wasm.wasm

      - name: Build Frontend
        run: |
          chmod +x updater.sh
          ./updater.sh

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: /tmp/zola

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 