name: Build and Deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rust-src

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Install Zola
        run: |
          wget https://github.com/getzola/zola/releases/download/v0.20.0/zola-v0.20.0-x86_64-unknown-linux-gnu.tar.gz
          tar xvf zola-v0.20.0-x86_64-unknown-linux-gnu.tar.gz
          sudo mv zola /usr/local/bin/

      - name: Build WASM
        run: |
          cd energysim-wasm
          wasm-pack build --target web --no-typescript --no-pack --dev
          mkdir -p ../static/pkg
          cp pkg/* ../static/pkg/

      - name: Build Zola
        run: |
          zola build --output-dir public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages 